# URL actualizada del Pooler (con los parámetros de seguridad necesarios)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

# Usuario y contraseña
spring.datasource.username=postgres.itkrfhzfbdtkoibpokbv
spring.datasource.password=Antojito111
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true