spring.config.import=optional:file:.env[.properties]
spring.application.name=maps-backend

# Database configuration (override using .env or system environment variables)
spring.datasource.url=${APP_DB_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${APP_DB_USERNAME:postgres.itkrfhzfbdtkoibpokbv}
spring.datasource.password=${APP_DB_PASSWORD:Antojito111}
spring.datasource.driver-class-name=${APP_DB_DRIVER:org.postgresql.Driver}

spring.jpa.database-platform=${APP_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${APP_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${APP_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:*}
app.r2.s3-api-url=${APP_R2_S3_API_URL:}
app.r2.endpoint=${APP_R2_ENDPOINT:}
app.r2.bucket=${APP_R2_BUCKET:}
app.r2.public-base-url=${APP_R2_PUBLIC_BASE_URL:}
app.r2.access-key-id=${APP_R2_ACCESS_KEY_ID:}
app.r2.secret-access-key=${APP_R2_SECRET_ACCESS_KEY:}
app.r2.upload-enabled=${APP_R2_UPLOAD_ENABLED:true}

server.error.include-message=always