# Conexión a Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.itkrfhzfbdtkoibpokbv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Antojito111
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false